config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root "events#index"

  devise_for :users,
            only: %i[ sessions registrations passwords ],
            controllers: {
              registrations: "users/registrations",
              passwords: "users/passwords",
              confirmations: "users/confirmations",
            }

  resources :events
  resources :reminders, only: %i[ create destroy ]
  
  post "/notifications" => "notifications#create", :as => :create
  post "/registration" => "notifications#registration"

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end
  mount Sidekiq::Web, at: "/sidekiq"
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, length: { minimum: 3, maximum: 50 }
  validates :description, length: { maximum: 600 }
  validates :starts_at, date: { after: Proc.new { Time.now },
                                message: "deve ser maior que a data atual!" }

  validates :ends_at, date: { after: :starts_at, message: "deve ser maior que a Data de início!" }
  validates :created_by_id, presence: true

  belongs_to :created_by, class_name: "User"

  has_many :reminders, dependent: :destroy
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ edit update destroy show ]
  include ApplicationHelper

  def index
    user = User.find(current_user.id)
    @events = user.events
  end

  def show
    if @event.created_by_id == current_user.id
      @reminder = current_user.reminders.new
    else
      redirect_to events_url, alert: "Não autorizado!"
    end
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params.merge(created_by: current_user))

    if @event.save
      redirect_to event_url(@event), notice: "Evento criado com sucesso!!"
    else
      flash.now[:alert] = @event.errors.full_messages
      render :new
    end
  end

  def update
    if @event.update(event_params)
      updateRemindAt(@event)
      redirect_to event_url(@event), notice: "Evento " + reminder_any?(@event) + " com sucesso!!"
    else
      flash.now[:alert] = @event.errors.full_messages
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: "Evento deletado com sucesso!!"
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :starts_at, :ends_at)
  end

  def reminder_any?(event)
    case
    when event.reminders.empty? == true
      return "atualizado"
    when event.reminders.length < 2
      return "e lembrete atualizado"
    when event.reminders.length > 1
      return "e lembretes atualizados"
    end
  end
end

app/views/events/_form.html.haml
= form_with(model: event, local: true) do |form|
  .form-event
    .form-group.mb-3.form-text
      = form.text_field :title, class: 'form-control', placeholder: "Título"
    .col-md-4.form-text
      = form.text_area :description, placeholder: "Descrição", class: "form-control h"
    .form-group.mb-3.form-text
      = form.label :starts_at, style: "display: block"
      = form.datetime_field :starts_at, class: "form-control"
    .form-group.mb-3.form-text
      = form.label :ends_at, style: "display: block"
      = form.datetime_field :ends_at, class: "form-control"
  .form-event-button
    = form.submit class: 'btn btn-primary hover-button ', data: { disable_with: 'Salvando...' }
    = link_to 'Cancelar', events_path, class: 'btn btn-light ms-5 hover-button '

app/views/events/_table_row.html.haml
%tr.border-top
  %td
    = truncate(event.title, length: 15)
  %td= l event.starts_at, format: :short2
  %td= l event.ends_at, format: :short2
  %td.text-right{:style => "padding-right: 0px;"}
    = link_to 'Ver', event, class: 'btn btn-secondary btn-sm hover-button '
    = link_to 'Editar', edit_event_path(event), class: 'btn btn-primary btn-sm hover-button '
    = link_to 'Apagar', event, method: :delete, class: 'btn btn-danger btn-sm hover-button ', data: { confirm: 'Tem certeza?' }

app/views/events/edit.html.haml
%h1.form-event Editar Evento
= render 'form', event: @event

app/views/events/index.html.haml
.row.mb-2
  .col-8
    %h1.display-4 Eventos
  .btn-new-event
    = link_to "+ Evento", new_event_path, class: 'btn btn-success hover-button'
- if @events.any?
  %table.table.table-borderless
    %thead
      %tr
        %th Título
        %th Data de início
        %th Data de fim
    %tbody
      - @events.each do |event|
        = render 'table_row', event: event
- else
  %p Nenhum evento cadastrado!

app/views/events/new.html.haml
%h1.form-event Novo Evento
= render 'form', event: @event

app/views/events/show.html.haml
.show-reminder
  .show-event
    %p
      %strong Título:
      = @event.title
    %p
      %strong Descrição:
      = truncate(@event.description, length: 30 )
      - if !@event.description.empty? && @event.description.length > 30
        = link_to 'Ler tudo...', "#", {                 |
          'class' => 'text-decoration-none fst-italic', |
          'data-bs-toggle' => "modal",                  |
          "data-bs-target" => "#modalDescription" }     |
    %p
      %strong Início:
      = l @event.starts_at, format: :short2
    %p
      %strong Fim:
      = l @event.ends_at, format: :short2
  %aside
    = link_to "#", {                                                   |
      'data-bs-toggle' => @event.reminders.length == 5 ? "" : "modal", |
      "data-bs-target" => "#staticBackdrop",                           |
      "title" => "No máximo 5 lembretes"                               |
      } do                                                             |
      .button-new-reminder
        = image_tag "lembrete.png"
    %section.reminders{"data-post-id" => "#{@event.id}"}
      %p.reminder-header Lembretes
      - if @event.reminders.any?
        %table.table.table-borderless
          %thead
            %tr
              %th N°
              %th Data de Lembrete
          %tbody
            - @event.reminders.order(reminder_at: :asc).each_with_index do |reminder, index|
              = render reminder, index: index
      - else
        %div
          %p Nenhum lembrete ainda!
.links-event
  = link_to 'Voltar', events_path, class: "btn btn-secondary hover-button"
  = link_to 'Editar', edit_event_path(@event), class: "btn btn-primary ms-2 hover-button"
/ Modal
#staticBackdrop.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "staticBackdropLabel", "data-bs-backdrop" => "static", "data-bs-keyboard" => "false", :tabindex => "-1"}
  .modal-dialog.modal-dialog-centered
    .modal-content
      .modal-body
        .new-reminder
          = render "reminders/form"
#modalDescription.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "staticBackdropLabel", "data-bs-keyboard" => "true", :tabindex => "-1"}
  .modal-dialog.modal-dialog-centered
    .modal-content
      .modal-body
        .new-reminder
          %p= @event.description